# Generated by Django 5.0.1 on 2024-02-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_gender', models.CharField(max_length=50)),
                ('emp_dept', models.CharField(max_length=50)),
                ('emp_salary', models.CharField(max_length=50)),
            ],
        ),
    ]
